<a href="https://colab.research.google.com/github/Saichand-design/python-2515/blob/main/DNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/content/diabetic.txt')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Age              40 non-null     int64  
 1   BMI              40 non-null     float64
 2   Blood Pressure   40 non-null     int64  
 3   Glucose Level    40 non-null     int64  
 4   Insulin Level    40 non-null     int64  
 5   Diabetic Status  40 non-null     object 
dtypes: float64(1), int64(4), object(1)
memory usage: 2.0+ KB


In [4]:
df['dstat'] = np.where(df['Diabetic Status']== 'Yes',1,0)
df

Age   BMI  Blood Pressure  Glucose Level  Insulin Level Diabetic Status  \
0    45  25.3             120            140             85             Yes   
1    50  28.1             130            155             90             Yes   
2    38  23.5             115            110             75              No   
3    60  31.2             135            160             95             Yes   
4    55  29.8             128            150             92             Yes   
5    32  22.7             110            105             70              No   
6    42  26.5             118            135             80              No   
7    48  27.3             125            145             88             Yes   
8    35  24.1             113            120             78              No   
9    58  30.5             132            158             93             Yes   
10   41  25.8             121            138             82              No   
11   47  27.0             126            144             87             Yes   
12   36  24.9             114            122             76              No   
13   53  29.1             130            148             89             Yes   
14   40  26.0             119            132             81              No   
15   61  31.5             136            162             96             Yes   
16   39  23.8             117            128             77              No   
17   49  27.5             129            146             90             Yes   
18   37  24.5             116            124             79              No   
19   54  30.0             133            150             91             Yes   
20   46  26.1             122            142             86             Yes   
21   51  28.5             131            156             91             Yes   
22   34  23.1             111            108             72              No   
23   62  32.0             137            164             97             Yes   
24   56  30.0             129            152             93             Yes   
25   30  22.0             109            104             68              No   
26   43  27.0             119            136             81              No   
27   49  28.0             124            146             89             Yes   
28   33  24.0             112            118             75              No   
29   59  31.0             134            160             94             Yes   
30   42  26.7             122            140             83              No   
31   48  28.2             127            149             88             Yes   
32   36  24.2             115            121             77              No   
33   52  29.5             129            151             90             Yes   
34   39  25.5             120            130             80              No   
35   63  32.5             138            165             98             Yes   
36   37  24.3             118            125             78              No   
37   50  27.8             130            147             91             Yes   
38   35  24.6             117            123             76              No   
39   55  30.5             132            153             92             Yes   

    dstat  
0       1  
1       1  
2       0  
3       1  
4       1  
5       0  
6       0  
7       1  
8       0  
9       1  
10      0  
11      1  
12      0  
13      1  
14      0  
15      1  
16      0  
17      1  
18      0  
19      1  
20      1  
21      1  
22      0  
23      1  
24      1  
25      0  
26      0  
27      1  
28      0  
29      1  
30      0  
31      1  
32      0  
33      1  
34      0  
35      1  
36      0  
37      1  
38      0  
39      1

In [24]:
inputs = df.drop(['Diabetic Status','dstat'],axis= 1)
inputs = inputs.to_numpy()
inputs.shape

(40, 5)

In [25]:
def scale(c):
   return (c-c.mean())/c.std()

In [26]:
def scaleMatrix(m):
  for i in range(m.shape[1]):
    m[:,i] = scale(m[:,i])
  return m


In [27]:
inputs_org = inputs.copy()

In [28]:
inputs = scaleMatrix(inputs)
inputs


array([[-0.10833785, -0.64639166, -0.4397378 ,  0.05643202,  0.02222603],
       [ 0.43335139,  0.35079658,  0.790298  ,  0.94746392,  0.65725547],
       [-0.86670278, -1.28744125, -1.05475569, -1.72563178, -1.24783285],
       [ 1.51672987,  1.45482642,  1.4053159 ,  1.24447455,  1.29228492],
       [ 0.97504063,  0.9562323 ,  0.54429084,  0.65045329,  0.91126725],
       [-1.51672987, -1.57235218, -1.66977359, -2.02264241, -1.8828623 ],
       [-0.43335139, -0.21902527, -0.68574496, -0.24057861, -0.61280341],
       [ 0.2166757 ,  0.06588565,  0.1752801 ,  0.35344265,  0.4032437 ],
       [-1.19171632, -1.07375805, -1.30076285, -1.13161051, -0.86681519],
       [ 1.30005417,  1.20552936,  1.03630516,  1.1256703 ,  1.03827314],
       [-0.54168924, -0.46832234, -0.31673422, -0.06237223, -0.35879163],
       [ 0.10833785, -0.04095595,  0.29828368,  0.29404053,  0.27623781],
       [-1.08337848, -0.78884713, -1.17775927, -1.01280626, -1.12082697],
       [ 0.75836493,  0.70693524,  0.7

In [29]:
for i in range(inputs.shape[1]):
  print(f"col {i} std {inputs[:,i].std()}")

col 0 std 1.0
col 1 std 1.0
col 2 std 1.0000000000000002
col 3 std 0.9999999999999999
col 4 std 0.9999999999999999


In [30]:
ones = np.ones(df['dstat'].count())
len(ones)

40

In [31]:
# feature Matrix
X = np.c_[ones,inputs]
X.shape

(40, 6)

In [33]:
# label Matrix
y = df['dstat'].to_numpy()
Y = np.c_[y]
Y.shape

(40, 1)

In [34]:
# random weight
np.random.seed(101)
W1 = np.random.random((6,8)) * 2-1
W2 = np.random.random((8,10)) * 2- 1
W3 = np.random.random((10,8))*2-1
W4 = np.random.random((8,1))* 2- 1


In [35]:
W1.shape

(6, 8)

In [36]:
W2.shape


(8, 10)

In [37]:
W3.shape

(10, 8)

In [38]:
W4.shape

(8, 1)

In [40]:
def sigmoid (x,w): #activation function at each layer
  return 1/(1+np.exp(-np.dot(x,w)))


In [41]:
def mse(y,ycap):
   return ((y - ycap)**2).mean()

In [42]:
def deriavte(p):
  return p*(1-p)


In [46]:
#Traing Loop
ploss = 0
flag = 0
conv = 0.0000001
for i in range(100000):
  #forward propagation
  a1 = sigmoid(X,W1)
  a2 = sigmoid(a1,W2)
  a3 = sigmoid(a2,W3)
  a4 = sigmoid(a3,W4)
  e4 = Y - a4
  closs = mse(Y,a4)
  delta4 = e4*deriavte(a4)
  e3 = delta4.dot(W4.T)
  delta3 = e3*deriavte(a3)
  e2 = delta3.dot(W3.T)
  delta2 = e2*deriavte(a2)
  e1 = delta2.dot(W2.T)
  delta1 = e1*deriavte(a1)
  W1 += X.T.dot(delta1) *0.02
  W2 += a1.T.dot(delta2) *0.02
  W3 += a2.T.dot(delta3) *0.02
  W4 += a3.T.dot(delta4) *0.02
  if np.abs(ploss - closs)<= conv:
    print(f"training complete adter{i+1} iteration")
    flag = 1
    break
  ploss = closs
if flag == 0:
  print(" bad training")

training complete adter4422 iteration


In [54]:
def predict(X,W): # W is array of [ W1,W2,W3,W4]
 a = X
 for i in range(len(W)):
  a = sigmoid(a,W[i])
  # iteration 1 -> sigmoid (X,W1)
  # iteraion 2 -> sigmoid(a,W2),
  # iteration 3 -> sigmoid(a,W3)
  # iteration 4 -> sigmoid (a,w4)
  return a


In [53]:
W = [W1,W2,W3,W4]

In [56]:
ycap = predict(X,W)
ycap.shape

(40, 8)

In [55]:
ycap

array([[0.66548264, 0.30431988, 0.36746766, 0.40919913, 0.3773709 ,
        0.63438502, 0.58163913, 0.61392324],
       [0.13686131, 0.07438971, 0.8695456 , 0.31445596, 0.16903784,
        0.91194123, 0.84415513, 0.22002425],
       [0.96818365, 0.98082474, 0.00860064, 0.41917702, 0.91396325,
        0.07720486, 0.1039357 , 0.96149086],
       [0.02445508, 0.00757189, 0.97936791, 0.22443293, 0.02704492,
        0.98205908, 0.95028819, 0.01706101],
       [0.10072421, 0.03016326, 0.89900131, 0.2704463 , 0.07253859,
        0.92833824, 0.83042516, 0.05470601],
       [0.99100613, 0.99749783, 0.00183665, 0.38317472, 0.98506399,
        0.02212558, 0.02094673, 0.9929906 ],
       [0.77093469, 0.78496931, 0.15190367, 0.26711155, 0.7910427 ,
        0.39553131, 0.18114785, 0.81119424],
       [0.32071812, 0.16385685, 0.65084475, 0.35037193, 0.24822164,
        0.79049849, 0.69335139, 0.32534806],
       [0.93942153, 0.9565099 , 0.02169913, 0.43301539, 0.9092792 ,
        0.09310883, 0.074112

In [52]:
yc = np.where(ycap > 0.5,1,0)
yc

array([[1, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [1,

In [ ]:
def accuracy(y,ycap):
  pcnt = np.where(y==ycap)[0].size
  n = y.shape