<a href="https://colab.research.google.com/github/Saichand-design/python-2515/blob/main/pratice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd


In [8]:
age = [20,30,25,40,27,28,22,24,31,29]
len(age)

10

In [9]:
exp = [0,5,2,10,4,3,5,1,2,6]
len(exp)

10

In [10]:
age = np.array(age)
exp = np.array(exp)

In [11]:
income = age**2 + exp *3+5
income

array([ 405,  920,  636, 1635,  746,  798,  504,  584,  972,  864])

In [12]:
np.c = [age,exp,income]

In [13]:
ones = np.ones(len(age))
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
X = np.c_[ones,age,exp]

In [15]:
X.shape


(10, 3)

In [16]:
Y = np.c_[income]

In [17]:
Y.shape

(10, 1)

In [18]:
W = np.random.random((3,1))

In [19]:
W

array([[0.00529473],
       [0.9852431 ],
       [0.6033142 ]])

In [20]:
#trail - 1


In [21]:
Ycap = X.dot(W)

In [22]:
Ycap

array([[19.71015669],
       [32.57915866],
       [25.84300058],
       [45.44816062],
       [29.02011517],
       [29.40204407],
       [24.69721388],
       [24.25444328],
       [31.75445917],
       [32.19722976]])

In [23]:
#loss
mse = ((Y-Ycap)**2).mean()


In [24]:
mse

np.float64(705873.7374800482)

In [25]:
#derivates
delta = X.T.dot(Y-Ycap)/len(age)


In [26]:
delta


array([[  776.90940181],
       [23129.2067082 ],
       [ 3655.42171969]])

In [27]:
#adjust weight

W+= delta *0.02
print("current loss",mse)
print("latest weight",W)

current loss 705873.7374800482
latest weight [[ 15.54348277]
 [463.56937726]
 [ 73.71174859]]


In [29]:
Ycap = X.dot(W)
Loss = ((Y-Ycap)**2).mean()
delta = X.T.dot(Y-Ycap)/Y.size
W+= delta *0.02
print("current loss",Loss)
print("latest weight",W)

current loss 156178974.92924768
latest weight [[ -230.13177603]
 [-6561.15688969]
 [ -961.57395824]]


In [ ]:
# based on above trails, Loss is Keep on increasing
#solution : scaling features and Labels.

In [30]:
def scale(X):
    return (X-X.mean())/X.std()

In [31]:
scale(age).std()

np.float64(1.0)

In [32]:
scale(exp).std()

np.float64(1.0)

In [33]:
scale(income).std()

np.float64(0.9999999999999997)

In [34]:
X_original = X.copy()
Y_original = Y.copy()
def scalematrix(X):
  for i in range(X.shape[1]):
    if i!=0:
      X[:,i] = scale(X[:,i])
  return X

In [35]:
X = scalematrix(X)
X

array([[ 1.        , -1.43014887, -1.38204664],
       [ 1.        ,  0.45162596,  0.43643578],
       [ 1.        , -0.48926145, -0.65465367],
       [ 1.        ,  2.33340078,  2.2549182 ],
       [ 1.        , -0.11290649,  0.0727393 ],
       [ 1.        ,  0.07527099, -0.29095719],
       [ 1.        , -1.0537939 ,  0.43643578],
       [ 1.        , -0.67743894, -1.01835015],
       [ 1.        ,  0.63980344, -0.65465367],
       [ 1.        ,  0.26344848,  0.80013226]])

In [36]:
Y = scale(Y)
Y

array([[-1.22998794],
       [ 0.34809823],
       [-0.52214734],
       [ 2.53903339],
       [-0.1850804 ],
       [-0.02573966],
       [-0.92662768],
       [-0.68148808],
       [ 0.50743897],
       [ 0.17650051]])

In [37]:
#trails after scaling

np.random.seed(101)
r = X.shape[1]
c = Y.shape[1]
W = np.random.random((r,c))*2-1
W

array([[ 0.03279726],
       [ 0.14133517],
       [-0.94305155]])

In [38]:
#trail 1
Ycap = X.dot(W)
Loss = ((Y-Ycap)**2).mean()
delta = X.T.dot(Y-Ycap)/Y.size
W+= delta *0.02
print("current loss",Loss)
print("latest weight",W)

current loss 2.9344051074576463
latest weight [[ 0.03214131]
 [ 0.17296994]
 [-0.91035727]]


In [39]:
#trail 2
Ycap = X.dot(W)
Loss = ((Y-Ycap)**2).mean()
delta = X.T.dot(Y-Ycap)/Y.size
W+= delta *0.02
print("current loss",Loss)
print("latest weight",W)


current loss 2.7310673451477183
latest weight [[ 0.03149848]
 [ 0.20346543]
 [-0.87880705]]


In [40]:
#trail 3
Ycap = X.dot(W)
Loss = ((Y-Ycap)**2).mean()
delta = X.T.dot(Y-Ycap)/Y.size
W+= delta *0.02
print("current loss",Loss)
print("latest weight",W)

current loss 2.5419035438957827
latest weight [[ 0.03086851]
 [ 0.23286214]
 [-0.84836036]]


In [48]:
Convergence = 0.000001
ploss = 0
for i in range(100000):
    Ycap = X.dot(W)
    Closs = ((Y-Ycap)**2).mean()
    if i%10000==0:
        print(f"current loss after {i+1} iteration,{Closs}")
    delta = X.T.dot(Y-Ycap)/Y.size
    W+= delta *0.02
    if np.abs(ploss - Closs)<= Convergence:
        print(f" Training is completed after {i+1} iteration")
        flag = 1
        break
    ploss = Closs
if flag==0:
    print("Training is not completed,run few more iterations")

current loss after 1 iteration,0.012421696730293367
 Training is completed after 2 iteration


In [49]:
W

array([[2.77779610e-16],
       [9.29928910e-01],
       [8.07110149e-02]])

In [52]:
Ycap = X.dot(W)
Y

array([[-1.22998794],
       [ 0.34809823],
       [-0.52214734],
       [ 2.53903339],
       [-0.1850804 ],
       [-0.02573966],
       [-0.92662768],
       [-0.68148808],
       [ 0.50743897],
       [ 0.17650051]])

In [54]:
np.c_[Y,Ycap]

array([[-1.22998794, -1.44148316],
       [ 0.34809823,  0.45520521],
       [-0.52214734, -0.50781613],
       [ 2.53903339,  2.35189358],
       [-0.1850804 , -0.09912415],
       [-0.02573966,  0.04651322],
       [-0.92662768, -0.94472824],
       [-0.68148808, -0.71216213],
       [ 0.50743897,  0.54213395],
       [ 0.17650051,  0.30956784]])

In [56]:
# R sqaure.
rss = ((Y-Ycap)**2).sum()
tss = ((Y-Y.mean())**2).sum()
rs = 1 - (rss/tss)
rs

np.float64(0.9875783032697066)

In [57]:
#gradient
# unscaling
Ycap

array([[-1.44148316],
       [ 0.45520521],
       [-0.50781613],
       [ 2.35189358],
       [-0.09912415],
       [ 0.04651322],
       [-0.94472824],
       [-0.71216213],
       [ 0.54213395],
       [ 0.30956784]])

In [58]:
#original
Y_original

array([[ 405],
       [ 920],
       [ 636],
       [1635],
       [ 746],
       [ 798],
       [ 504],
       [ 584],
       [ 972],
       [ 864]])

In [59]:
Ystd = Y_original.std()
Ymean = Y_original.mean()
Ystd,Ymean

(np.float64(326.3446644270441), np.float64(806.4))

In [61]:
Y = Ystd*Ycap + Ymean
Y

array([[ 335.9796607 ],
       [ 954.95379136],
       [ 640.67691442],
       [1573.92792202],
       [ 774.05136376],
       [ 821.57934202],
       [ 498.09297966],
       [ 573.98968976],
       [ 983.3225232 ],
       [ 907.4258131 ]])

In [62]:
np.c_[Y_original,Y]

array([[ 405.        ,  335.9796607 ],
       [ 920.        ,  954.95379136],
       [ 636.        ,  640.67691442],
       [1635.        , 1573.92792202],
       [ 746.        ,  774.05136376],
       [ 798.        ,  821.57934202],
       [ 504.        ,  498.09297966],
       [ 584.        ,  573.98968976],
       [ 972.        ,  983.3225232 ],
       [ 864.        ,  907.4258131 ]])

In [65]:
# R square
rss = ((Y_original-Y)**2).sum()
tss = ((Y_original-Y.mean())**2).sum()
rs = 1 - (rss/tss)
print("Model Accurarcy", rs*100)

Model Accurarcy 98.75783032697066


In [ ]:


--------
input file: diabetic_score.txt

Age,BMI,Blood Pressure,Glucose Level,Insulin Level,Diabetic Status,diabetic_score
45,25.3,120,140,85,Yes,73.15
50,28.1,130,155,90,Yes,80.05
38,23.5,115,110,75,No,64.25
60,31.2,135,160,95,Yes,84.1
55,29.8,128,150,92,Yes,79.7
32,22.7,110,105,70,No,61.35
42,26.5,118,135,80,No,71.85
48,27.3,125,145,88,Yes,76.45
35,24.1,113,120,78,No,66.45
58,30.5,132,158,93,Yes,82.55
41,25.8,121,138,82,No,72.9
47,27.0,126,144,87,Yes,76.2
36,24.9,114,122,76,No,67.25
53,29.1,130,148,89,Yes,79.05000000000001
40,26.0,119,132,81,No,71.3
61,31.5,136,162,96,Yes,84.94999999999999
39,23.8,117,128,77,No,68.60000000000001
49,27.5,129,146,90,Yes,77.75
37,24.5,116,124,79,No,68.15
54,30.0,133,150,91,Yes,80.69999999999999




In [ ]:
# task : based on age,bmi,bp,glucose level,insulin level predict Diabetic sscores

In [ ]:
#statistical Approach

In [66]:
!pwd

/content


In [67]:
import pandas as pd
import numpy as np


In [70]:
df = pd.read_csv('/content/diabetic_scores.txt')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Age              20 non-null     int64  
 1   BMI              20 non-null     float64
 2   Blood Pressure   20 non-null     int64  
 3   Glucose Level    20 non-null     int64  
 4   Insulin Level    20 non-null     int64  
 5   Diabetic Status  20 non-null     object 
 6   diabetic_score   20 non-null     float64
dtypes: float64(2), int64(4), object(1)
memory usage: 1.2+ KB


In [71]:
xdf = df.drop(columns=['Diabetic Status','diabetic_score'],axis =1)
xdf

Age   BMI  Blood Pressure  Glucose Level  Insulin Level
0    45  25.3             120            140             85
1    50  28.1             130            155             90
2    38  23.5             115            110             75
3    60  31.2             135            160             95
4    55  29.8             128            150             92
5    32  22.7             110            105             70
6    42  26.5             118            135             80
7    48  27.3             125            145             88
8    35  24.1             113            120             78
9    58  30.5             132            158             93
10   41  25.8             121            138             82
11   47  27.0             126            144             87
12   36  24.9             114            122             76
13   53  29.1             130            148             89
14   40  26.0             119            132             81
15   61  31.5             136            162             96
16   39  23.8             117            128             77
17   49  27.5             129            146             90
18   37  24.5             116            124             79
19   54  30.0             133            150             91

In [72]:
inputs = xdf.to_numpy()
inputs

array([[ 45. ,  25.3, 120. , 140. ,  85. ],
       [ 50. ,  28.1, 130. , 155. ,  90. ],
       [ 38. ,  23.5, 115. , 110. ,  75. ],
       [ 60. ,  31.2, 135. , 160. ,  95. ],
       [ 55. ,  29.8, 128. , 150. ,  92. ],
       [ 32. ,  22.7, 110. , 105. ,  70. ],
       [ 42. ,  26.5, 118. , 135. ,  80. ],
       [ 48. ,  27.3, 125. , 145. ,  88. ],
       [ 35. ,  24.1, 113. , 120. ,  78. ],
       [ 58. ,  30.5, 132. , 158. ,  93. ],
       [ 41. ,  25.8, 121. , 138. ,  82. ],
       [ 47. ,  27. , 126. , 144. ,  87. ],
       [ 36. ,  24.9, 114. , 122. ,  76. ],
       [ 53. ,  29.1, 130. , 148. ,  89. ],
       [ 40. ,  26. , 119. , 132. ,  81. ],
       [ 61. ,  31.5, 136. , 162. ,  96. ],
       [ 39. ,  23.8, 117. , 128. ,  77. ],
       [ 49. ,  27.5, 129. , 146. ,  90. ],
       [ 37. ,  24.5, 116. , 124. ,  79. ],
       [ 54. ,  30. , 133. , 150. ,  91. ]])

In [73]:
ones = np.ones(df['Age'].count())
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [74]:
X = np.c_[ones,inputs]
X.shape

(20, 6)

In [75]:
outputs = df['diabetic_score'].to_numpy()
outputs

array([73.15, 80.05, 64.25, 84.1 , 79.7 , 61.35, 71.85, 76.45, 66.45,
       82.55, 72.9 , 76.2 , 67.25, 79.05, 71.3 , 84.95, 68.6 , 77.75,
       68.15, 80.7 ])

In [76]:
Y = np.c_[outputs]
Y.shape

(20, 1)

In [88]:
from numpy.linalg import inv
W = inv(X.T.dot(X)).dot(X.T.dot(Y))
W

array([[2.00088834e-10],
       [5.68434189e-13],
       [5.00000000e-01],
       [2.00000000e-01],
       [2.00000000e-01],
       [1.00000000e-01]])

In [89]:
def predict(X,W):
  return X.dot(W)

In [87]:

def rsquare(Y,Ycap):
  rss = ((Y-Ycap)**2).sum()
  tss = ((Y-Y.mean())**2).sum()
  rs= 1 - rss/tss
  return rs

In [90]:
Ycap_stats = predict(X,W)
Ycap_stats

array([[73.15],
       [80.05],
       [64.25],
       [84.1 ],
       [79.7 ],
       [61.35],
       [71.85],
       [76.45],
       [66.45],
       [82.55],
       [72.9 ],
       [76.2 ],
       [67.25],
       [79.05],
       [71.3 ],
       [84.95],
       [68.6 ],
       [77.75],
       [68.15],
       [80.7 ]])

In [91]:
rsquare(Y,Ycap_stats)


np.float64(1.0)

In [92]:
inputs

array([[ 45. ,  25.3, 120. , 140. ,  85. ],
       [ 50. ,  28.1, 130. , 155. ,  90. ],
       [ 38. ,  23.5, 115. , 110. ,  75. ],
       [ 60. ,  31.2, 135. , 160. ,  95. ],
       [ 55. ,  29.8, 128. , 150. ,  92. ],
       [ 32. ,  22.7, 110. , 105. ,  70. ],
       [ 42. ,  26.5, 118. , 135. ,  80. ],
       [ 48. ,  27.3, 125. , 145. ,  88. ],
       [ 35. ,  24.1, 113. , 120. ,  78. ],
       [ 58. ,  30.5, 132. , 158. ,  93. ],
       [ 41. ,  25.8, 121. , 138. ,  82. ],
       [ 47. ,  27. , 126. , 144. ,  87. ],
       [ 36. ,  24.9, 114. , 122. ,  76. ],
       [ 53. ,  29.1, 130. , 148. ,  89. ],
       [ 40. ,  26. , 119. , 132. ,  81. ],
       [ 61. ,  31.5, 136. , 162. ,  96. ],
       [ 39. ,  23.8, 117. , 128. ,  77. ],
       [ 49. ,  27.5, 129. , 146. ,  90. ],
       [ 37. ,  24.5, 116. , 124. ,  79. ],
       [ 54. ,  30. , 133. , 150. ,  91. ]])

In [93]:
X_scale = scalematrix(X)
X_scale

array([[ 1.        , -0.11632626, -0.62884247, -0.42953131,  0.08787149,
         0.04136063],
       [ 1.        ,  0.46530506,  0.4350602 ,  0.8526517 ,  1.02935178,
         0.73070439],
       [ 1.        , -0.93061011, -1.31277989, -1.07062281, -1.79508907,
        -1.33732691],
       [ 1.        ,  1.6285677 ,  1.61295243,  1.4937432 ,  1.34317854,
         1.42004816],
       [ 1.        ,  1.04693638,  1.0810011 ,  0.5962151 ,  0.71552502,
         1.0064419 ],
       [ 1.        , -1.6285677 , -1.61675208, -1.71171431, -2.10891584,
        -2.02667068],
       [ 1.        , -0.46530506, -0.17288418, -0.68596791, -0.22595527,
        -0.64798314],
       [ 1.        ,  0.23265253,  0.13108801,  0.2115602 ,  0.40169825,
         0.45496689],
       [ 1.        , -1.27958891, -1.08480075, -1.32705941, -1.16743555,
        -0.92372065],
       [ 1.        ,  1.39591517,  1.34697676,  1.1090883 ,  1.21764783,
         1.14431065],
       [ 1.        , -0.58163132, -0.43885985, -0.

In [99]:
Y_scale = scale(Y)
Y_scale

array([[-0.17781366],
       [ 0.8553773 ],
       [-1.51048026],
       [ 1.46181547],
       [ 0.80296906],
       [-1.94471994],
       [-0.37247283],
       [ 0.31632114],
       [-1.18105705],
       [ 1.22972185],
       [-0.21524812],
       [ 0.27888669],
       [-1.0612668 ],
       [ 0.70563948],
       [-0.45482863],
       [ 1.58909261],
       [-0.85912074],
       [ 0.51098031],
       [-0.92650276],
       [ 0.95270688]])

In [95]:
for i in range(X_scale.shape[1]):
  if i!=0:
   print(X_scale[:,i].std())

1.0000000000000002
1.0000000000000002
1.0
1.0
1.0


In [100]:
Y_scale.std()

np.float64(0.9999999999999999)

In [101]:
#random weights
np.random.seed(101)
r = X.shape[1]
c = Y.shape[1]
W = np.random.random((r,c))*2-1
W

array([[ 0.03279726],
       [ 0.14133517],
       [-0.94305155],
       [-0.65695669],
       [ 0.37055396],
       [ 0.66779373]])

In [102]:
def mse(Y,Ycap):
  return ((Y-Ycap)**2).mean()

In [103]:
#training
Convergence = 0.0000001
flag =0
ploss = 0
for i in range(100000):
  Ycap = predict(X_scale,W)
  Closs = mse(Y_scale,Ycap)
  if i%1000==0:
    print(f"current loss after {i+1} iteration,{Closs}")
  delta = X_scale.T.dot(Y_scale - Ycap)/Y_scale.size
  W+= delta *0.02
  if np.abs(ploss - Closs)<= Convergence:
    print(f" Training is completed after {i+1} iteration")
    flag = 1
    break
  ploss = Closs
if flag==0:
  print("training not completed")

current loss after 1 iteration,2.0583367158430237
current loss after 1001 iteration,0.015463606251676084
current loss after 2001 iteration,0.005348726014160628
current loss after 3001 iteration,0.002042420760629099
current loss after 4001 iteration,0.0007923782661203203
current loss after 5001 iteration,0.00030886982594514775
current loss after 6001 iteration,0.00012071018425495381
 Training is completed after 6135 iteration


In [104]:
Ycap_ML = predict(X_scale,W)
Ycap_ML

array([[-0.15271154],
       [ 0.84234562],
       [-1.50066084],
       [ 1.46363609],
       [ 0.82236761],
       [-1.94810057],
       [-0.37688041],
       [ 0.32399217],
       [-1.17280853],
       [ 1.23601321],
       [-0.22834975],
       [ 0.27546041],
       [-1.06900901],
       [ 0.69940925],
       [-0.46385624],
       [ 1.59099104],
       [-0.86052427],
       [ 0.50867973],
       [-0.92600097],
       [ 0.936007  ]])

In [106]:
acc = rsquare(Y_scale,Ycap_ML)*100
acc

np.float64(99.98936524257567)