<a href="https://colab.research.google.com/github/Saichand-design/python-2515/blob/main/Logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
# This is formatted as code
```
input file : diabetic.txt

Age,BMI,Blood Pressure,Glucose Level,Insulin Level,Diabetic Status
45,25.3,120,140,85,Yes
50,28.1,130,155,90,Yes
38,23.5,115,110,75,No
60,31.2,135,160,95,Yes
55,29.8,128,150,92,Yes
32,22.7,110,105,70,No
42,26.5,118,135,80,No
48,27.3,125,145,88,Yes
35,24.1,113,120,78,No
58,30.5,132,158,93,Yes
41,25.8,121,138,82,No
47,27.0,126,144,87,Yes
36,24.9,114,122,76,No
53,29.1,130,148,89,Yes
40,26.0,119,132,81,No
61,31.5,136,162,96,Yes
39,23.8,117,128,77,No
49,27.5,129,146,90,Yes
37,24.5,116,124,79,No
54,30.0,133,150,91,Yes
46,26.1,122,142,86,Yes
51,28.5,131,156,91,Yes
34,23.1,111,108,72,No
62,32.0,137,164,97,Yes
56,30.0,129,152,93,Yes
30,22.0,109,104,68,No
43,27.0,119,136,81,No
49,28.0,124,146,89,Yes
33,24.0,112,118,75,No
59,31.0,134,160,94,Yes
42,26.7,122,140,83,No
48,28.2,127,149,88,Yes
36,24.2,115,121,77,No
52,29.5,129,151,90,Yes
39,25.5,120,130,80,No
63,32.5,138,165,98,Yes
37,24.3,118,125,78,No


In [2]:
import pandas as pd
import numpy as np


In [3]:
df = pd.read_csv("/content/diabetic.txt")
df

Age   BMI  Blood Pressure  Glucose Level  Insulin Level Diabetic Status
0    45  25.3             120            140             85             Yes
1    50  28.1             130            155             90             Yes
2    38  23.5             115            110             75              No
3    60  31.2             135            160             95             Yes
4    55  29.8             128            150             92             Yes
5    32  22.7             110            105             70              No
6    42  26.5             118            135             80              No
7    48  27.3             125            145             88             Yes
8    35  24.1             113            120             78              No
9    58  30.5             132            158             93             Yes
10   41  25.8             121            138             82              No
11   47  27.0             126            144             87             Yes
12   36  24.9             114            122             76              No
13   53  29.1             130            148             89             Yes
14   40  26.0             119            132             81              No
15   61  31.5             136            162             96             Yes
16   39  23.8             117            128             77              No
17   49  27.5             129            146             90             Yes
18   37  24.5             116            124             79              No
19   54  30.0             133            150             91             Yes
20   46  26.1             122            142             86             Yes
21   51  28.5             131            156             91             Yes
22   34  23.1             111            108             72              No
23   62  32.0             137            164             97             Yes
24   56  30.0             129            152             93             Yes
25   30  22.0             109            104             68              No
26   43  27.0             119            136             81              No
27   49  28.0             124            146             89             Yes
28   33  24.0             112            118             75              No
29   59  31.0             134            160             94             Yes
30   42  26.7             122            140             83              No
31   48  28.2             127            149             88             Yes
32   36  24.2             115            121             77              No
33   52  29.5             129            151             90             Yes
34   39  25.5             120            130             80              No
35   63  32.5             138            165             98             Yes
36   37  24.3             118            125             78              No
37   50  27.8             130            147             91             Yes
38   35  24.6             117            123             76              No
39   55  30.5             132            153             92             Yes

In [6]:
df['dstat'] = np.where(df['Diabetic Status'] == 'Yes', 1, 0)
df['dstat']

0     1
1     1
2     0
3     1
4     1
5     0
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    1
14    0
15    1
16    0
17    1
18    0
19    1
20    1
21    1
22    0
23    1
24    1
25    0
26    0
27    1
28    0
29    1
30    0
31    1
32    0
33    1
34    0
35    1
36    0
37    1
38    0
39    1
Name: dstat, dtype: int64

In [16]:
xdf = df.drop(['Diabetic Status','dstat'],axis =1)
ones = np.ones(df["Age"].count())
X = np.c_[ones,xdf]
X.shape

(40, 6)

In [19]:
y= df['dstat'].to_numpy()
y = np.c_[y]
y.shape

(40, 1)

In [21]:
# statistical way :
def weights(x,y):
  from numpy.linalg import inv
  left = inv(x.T.dot(x))
  rgt = x.T.dot(y)
  return left.dot(rgt)

In [24]:
W = weights(X,y)
W

array([[-2.35956472e+00],
       [ 5.08182098e-02],
       [-1.99938149e-01],
       [ 2.00833029e-03],
       [-7.38042301e-03],
       [ 7.98269188e-02]])

In [25]:
# predication
def predict(X,W):
  return 1/(1+np.exp(-X.dot(W)))


In [26]:
ycap = predict(X,W)
ycap

array([[0.70304662],
       [0.7036258 ],
       [0.56932829],
       [0.75496527],
       [0.72539036],
       [0.44074927],
       [0.52578174],
       [0.6957301 ],
       [0.54198924],
       [0.73354315],
       [0.58319292],
       [0.68260553],
       [0.47173387],
       [0.68761149],
       [0.55120181],
       [0.76551963],
       [0.57463092],
       [0.73070138],
       [0.56127664],
       [0.69227318],
       [0.69461797],
       [0.71298412],
       [0.48077456],
       [0.76872157],
       [0.7406336 ],
       [0.4123926 ],
       [0.53208646],
       [0.69175701],
       [0.46505273],
       [0.73742081],
       [0.56803607],
       [0.65058175],
       [0.52896433],
       [0.67125356],
       [0.54775915],
       [0.77318971],
       [0.55061152],
       [0.74335417],
       [0.47368   ],
       [0.69366177]])

In [28]:
ycap.shape

(40, 1)

In [30]:
np.c_[y,ycap]

array([[1.        , 0.70304662],
       [1.        , 0.7036258 ],
       [0.        , 0.56932829],
       [1.        , 0.75496527],
       [1.        , 0.72539036],
       [0.        , 0.44074927],
       [0.        , 0.52578174],
       [1.        , 0.6957301 ],
       [0.        , 0.54198924],
       [1.        , 0.73354315],
       [0.        , 0.58319292],
       [1.        , 0.68260553],
       [0.        , 0.47173387],
       [1.        , 0.68761149],
       [0.        , 0.55120181],
       [1.        , 0.76551963],
       [0.        , 0.57463092],
       [1.        , 0.73070138],
       [0.        , 0.56127664],
       [1.        , 0.69227318],
       [1.        , 0.69461797],
       [1.        , 0.71298412],
       [0.        , 0.48077456],
       [1.        , 0.76872157],
       [1.        , 0.7406336 ],
       [0.        , 0.4123926 ],
       [0.        , 0.53208646],
       [1.        , 0.69175701],
       [0.        , 0.46505273],
       [1.        , 0.73742081],
       [0.

In [34]:
yc = np.where(ycap>0.5,1,0)
yc

array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1]])

In [35]:
np.c_[y,yc]

array([[1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1]])

In [40]:
np.where(y==yc)[0].size

28

In [53]:
def accuracy(y,ycap):
  pcnt = np.where(y==ycap)[0].size
  n = y.shape[0]
  acc = round(pcnt/n*100,2)
  return acc

In [54]:
accuracy(y,yc)

70.0

In [56]:
from sklearn.metrics import accuracy_score
accuracy_score(y,yc)

0.7

In [61]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X,y)
yc = model.predict(X)
acc = accuracy_score(y,yc)
acc

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


100.0