<a href="https://colab.research.google.com/github/Saichand-design/python-2515/blob/main/Logistic_regression_with_GDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


In [4]:
df = pd.read_csv('/content/diabetic.txt')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Age              40 non-null     int64  
 1   BMI              40 non-null     float64
 2   Blood Pressure   40 non-null     int64  
 3   Glucose Level    40 non-null     int64  
 4   Insulin Level    40 non-null     int64  
 5   Diabetic Status  40 non-null     object 
dtypes: float64(1), int64(4), object(1)
memory usage: 2.0+ KB


In [5]:
df['Diabetic Status']

0     Yes
1     Yes
2      No
3     Yes
4     Yes
5      No
6      No
7     Yes
8      No
9     Yes
10     No
11    Yes
12     No
13    Yes
14     No
15    Yes
16     No
17    Yes
18     No
19    Yes
20    Yes
21    Yes
22     No
23    Yes
24    Yes
25     No
26     No
27    Yes
28     No
29    Yes
30     No
31    Yes
32     No
33    Yes
34     No
35    Yes
36     No
37    Yes
38     No
39    Yes
Name: Diabetic Status, dtype: object

In [7]:
df['dstat'] = np.where(df['Diabetic Status']=='Yes',1,0)
df

Age   BMI  Blood Pressure  Glucose Level  Insulin Level Diabetic Status  \
0    45  25.3             120            140             85             Yes   
1    50  28.1             130            155             90             Yes   
2    38  23.5             115            110             75              No   
3    60  31.2             135            160             95             Yes   
4    55  29.8             128            150             92             Yes   
5    32  22.7             110            105             70              No   
6    42  26.5             118            135             80              No   
7    48  27.3             125            145             88             Yes   
8    35  24.1             113            120             78              No   
9    58  30.5             132            158             93             Yes   
10   41  25.8             121            138             82              No   
11   47  27.0             126            144             87             Yes   
12   36  24.9             114            122             76              No   
13   53  29.1             130            148             89             Yes   
14   40  26.0             119            132             81              No   
15   61  31.5             136            162             96             Yes   
16   39  23.8             117            128             77              No   
17   49  27.5             129            146             90             Yes   
18   37  24.5             116            124             79              No   
19   54  30.0             133            150             91             Yes   
20   46  26.1             122            142             86             Yes   
21   51  28.5             131            156             91             Yes   
22   34  23.1             111            108             72              No   
23   62  32.0             137            164             97             Yes   
24   56  30.0             129            152             93             Yes   
25   30  22.0             109            104             68              No   
26   43  27.0             119            136             81              No   
27   49  28.0             124            146             89             Yes   
28   33  24.0             112            118             75              No   
29   59  31.0             134            160             94             Yes   
30   42  26.7             122            140             83              No   
31   48  28.2             127            149             88             Yes   
32   36  24.2             115            121             77              No   
33   52  29.5             129            151             90             Yes   
34   39  25.5             120            130             80              No   
35   63  32.5             138            165             98             Yes   
36   37  24.3             118            125             78              No   
37   50  27.8             130            147             91             Yes   
38   35  24.6             117            123             76              No   
39   55  30.5             132            153             92             Yes   

    dstat  
0       1  
1       1  
2       0  
3       1  
4       1  
5       0  
6       0  
7       1  
8       0  
9       1  
10      0  
11      1  
12      0  
13      1  
14      0  
15      1  
16      0  
17      1  
18      0  
19      1  
20      1  
21      1  
22      0  
23      1  
24      1  
25      0  
26      0  
27      1  
28      0  
29      1  
30      0  
31      1  
32      0  
33      1  
34      0  
35      1  
36      0  
37      1  
38      0  
39      1

In [15]:
inputs = df.drop(['Diabetic Status','dstat'],axis= 1)
inputs = inputs.to_numpy()
inputs.shape

(40, 5)

In [10]:
inputs_original = inputs.copy()

In [12]:
def scale(x):
  return (x - x.mean())/x.std()
def scalemetrix(x):
    for i in range(x.shape[1]):
        x[:,i] = scale(x[:,i])
    return x

In [16]:
inputs = scalemetrix(inputs)
inputs

array([[-0.10833785, -0.64639166, -0.4397378 ,  0.05643202,  0.02222603],
       [ 0.43335139,  0.35079658,  0.790298  ,  0.94746392,  0.65725547],
       [-0.86670278, -1.28744125, -1.05475569, -1.72563178, -1.24783285],
       [ 1.51672987,  1.45482642,  1.4053159 ,  1.24447455,  1.29228492],
       [ 0.97504063,  0.9562323 ,  0.54429084,  0.65045329,  0.91126725],
       [-1.51672987, -1.57235218, -1.66977359, -2.02264241, -1.8828623 ],
       [-0.43335139, -0.21902527, -0.68574496, -0.24057861, -0.61280341],
       [ 0.2166757 ,  0.06588565,  0.1752801 ,  0.35344265,  0.4032437 ],
       [-1.19171632, -1.07375805, -1.30076285, -1.13161051, -0.86681519],
       [ 1.30005417,  1.20552936,  1.03630516,  1.1256703 ,  1.03827314],
       [-0.54168924, -0.46832234, -0.31673422, -0.06237223, -0.35879163],
       [ 0.10833785, -0.04095595,  0.29828368,  0.29404053,  0.27623781],
       [-1.08337848, -0.78884713, -1.17775927, -1.01280626, -1.12082697],
       [ 0.75836493,  0.70693524,  0.7

In [17]:
ones = np.ones(inputs.shape[0])
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [18]:
#feature metrix
X = np.column_stack((ones,inputs))
X.shape

(40, 6)

In [19]:
Y = df['dstat'].to_numpy()
Y = np.c_[Y]
Y.shape


(40, 1)

In [22]:
#intittiate Random weights
np.random.seed(101)
r = X.shape[1]
c = Y.shape[1]
W = np.random.random((r,c))*2 -1
W.shape
W

array([[ 0.03279726],
       [ 0.14133517],
       [-0.94305155],
       [-0.65695669],
       [ 0.37055396],
       [ 0.66779373]])

In [ ]:
# note : for classification model, no need to scale label


In [23]:
def predict(x,w):
    return 1/(1+np.exp(-np.dot(x,w)))
def mse (y,ycap):
    return ((y - ycap)**2).mean()
def derivate(p): #on crossEntropy
    return p*(1-p)

In [26]:
# training Loop
conv = 0.0000001
ploss = 0
flog = 0
for i in range(1000000):
    ycap = predict(X,W)
    e = Y - ycap
    closs = mse(Y,ycap)
    if i%1000 == 0:
      print(f"current loss after {i+1} iterations {closs}")
    delta = e*derivate(ycap)
    W+= X.T.dot(delta)*0.02
    if np.abs(ploss-closs)<= conv:
      print(f"Training completed after {i +1} iterations")
      flag = 1
      break
    ploss = closs

if flag == 0:
  print("Training not completed, run few more iterations")


current loss after 1 iterations 0.33344613722423133
current loss after 1001 iterations 0.006610954636553526
current loss after 2001 iterations 0.003970602102366896
current loss after 3001 iterations 0.0027920666560854067
current loss after 4001 iterations 0.0021309638219498403
current loss after 5001 iterations 0.0017120111198775782
current loss after 6001 iterations 0.0014247679502665648
current loss after 7001 iterations 0.0012165787815362878
current loss after 8001 iterations 0.0010593069406707582
current loss after 9001 iterations 0.0009366255717780582
Training completed after 9403 iterations


In [27]:
W

array([[ 0.63162072],
       [ 4.62159437],
       [-2.62250592],
       [ 0.05695129],
       [ 2.46908405],
       [ 5.15206851]])

In [28]:
ycap = predict(X,W)
ycap

array([[8.86441288e-01],
       [9.99438889e-01],
       [2.15023761e-05],
       [9.99998804e-01],
       [9.99871836e-01],
       [3.96017691e-08],
       [1.00804420e-02],
       [9.88113844e-01],
       [8.32079301e-05],
       [9.99991420e-01],
       [6.51174160e-02],
       [9.67888916e-01],
       [2.37260110e-05],
       [9.98294365e-01],
       [7.39092392e-03],
       [9.99999631e-01],
       [1.40812227e-03],
       [9.98010137e-01],
       [5.50433532e-04],
       [9.99526680e-01],
       [9.41038482e-01],
       [9.99779667e-01],
       [4.29391074e-07],
       [9.99999863e-01],
       [9.99963953e-01],
       [6.48122501e-09],
       [2.30830341e-02],
       [9.93702848e-01],
       [3.49055505e-06],
       [9.99996829e-01],
       [1.14110238e-01],
       [9.84939892e-01],
       [7.63235685e-05],
       [9.98621213e-01],
       [2.80242058e-03],
       [9.99999941e-01],
       [4.05038874e-04],
       [9.99287641e-01],
       [2.25054340e-05],
       [9.99845678e-01]])

In [29]:
# convert probilities into numeric Labels
yc = np.where(ycap>0.5,1,0)
yc

array([[1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1]])

In [30]:
np.c_[Y,yc]

array([[1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1]])

In [35]:
pcnt = np.where(Y==yc)[0].size
n = Y.shape[0]
acc = pcnt/n*100
acc

100.0

In [37]:
def accuracy(y,ycap):
     pcnt = np.where(y==ycap)[0].size
     n = y.shape[0]
     acc = pcnt/n*100
     return acc

In [38]:
accuracy(Y,yc)

100.0

In [40]:
# do same with sklearn liberary
inputs

Age   BMI  Blood Pressure  Glucose Level  Insulin Level
0    45  25.3             120            140             85
1    50  28.1             130            155             90
2    38  23.5             115            110             75
3    60  31.2             135            160             95
4    55  29.8             128            150             92
5    32  22.7             110            105             70
6    42  26.5             118            135             80
7    48  27.3             125            145             88
8    35  24.1             113            120             78
9    58  30.5             132            158             93
10   41  25.8             121            138             82
11   47  27.0             126            144             87
12   36  24.9             114            122             76
13   53  29.1             130            148             89
14   40  26.0             119            132             81
15   61  31.5             136            162             96
16   39  23.8             117            128             77
17   49  27.5             129            146             90
18   37  24.5             116            124             79
19   54  30.0             133            150             91
20   46  26.1             122            142             86
21   51  28.5             131            156             91
22   34  23.1             111            108             72
23   62  32.0             137            164             97
24   56  30.0             129            152             93
25   30  22.0             109            104             68
26   43  27.0             119            136             81
27   49  28.0             124            146             89
28   33  24.0             112            118             75
29   59  31.0             134            160             94
30   42  26.7             122            140             83
31   48  28.2             127            149             88
32   36  24.2             115            121             77
33   52  29.5             129            151             90
34   39  25.5             120            130             80
35   63  32.5             138            165             98
36   37  24.3             118            125             78
37   50  27.8             130            147             91
38   35  24.6             117            123             76
39   55  30.5             132            153             92

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model = LogisticRegression()
model.fit(inputs_original,Y)
yc = model.predict(inputs_original)
accuracy_score(Y,yc)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


1.0