<a href="https://colab.research.google.com/github/Saichand-design/python-2515/blob/main/pratice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
age = [20,30,25,40,27,28,22,24,31,29]
len(age)

10

In [ ]:
exp = [0,5,2,10,4,3,5,1,2,6]
len(exp)

10

In [ ]:
age = np.array(age)
exp = np.array(exp)

In [ ]:
income = age**2 + exp *3+5
income

array([ 405,  920,  636, 1635,  746,  798,  504,  584,  972,  864])

In [ ]:
np.c = [age,exp,income]

In [ ]:
ones = np.ones(len(age))
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
X = np.c_[ones,age,exp]

In [ ]:
X.shape


(10, 3)

In [ ]:
Y = np.c_[income]

In [ ]:
Y.shape

(10, 1)

In [ ]:
W = np.random.random((3,1))

In [ ]:
W

array([[0.70622897],
       [0.92188303],
       [0.30532616]])

In [ ]:
#trail - 1


In [ ]:
Ycap = X.dot(W)

In [ ]:
Ycap

array([[19.14388958],
       [29.88935069],
       [24.36395705],
       [40.63481179],
       [26.81837543],
       [27.43493231],
       [22.51428644],
       [23.13674786],
       [29.89525524],
       [29.27279381]])

In [ ]:
#loss
mse = ((Y-Ycap)**2).mean()


In [ ]:
mse

np.float64(709900.057984919)

In [ ]:
#derivates
delta = X.T.dot(Y-Ycap)/len(age)


In [ ]:
delta


array([[  779.08955998],
       [23194.54158652],
       [ 3666.67634625]])

In [ ]:
#adjust weight

W+= delta *0.02
print("current loss",mse)
print("latest weight",W)

current loss 709900.057984919
latest weight [[ 31.86981137]
 [928.70354649]
 [146.97238001]]
