<a href="https://colab.research.google.com/github/Saichand-design/python-2515/blob/main/Sklearn_experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.linear_model import LinearRegression

input file :

Age,BMI,Blood Pressure,Glucose Level,Insulin Level,Diabetic Status,diabetic_score
45,25.3,120,140,85,Yes,73.15
50,28.1,130,155,90,Yes,80.05
38,23.5,115,110,75,No,64.25
60,31.2,135,160,95,Yes,84.1
55,29.8,128,150,92,Yes,79.7
32,22.7,110,105,70,No,61.35
42,26.5,118,135,80,No,71.85
48,27.3,125,145,88,Yes,76.45
35,24.1,113,120,78,No,66.45
58,30.5,132,158,93,Yes,82.55
41,25.8,121,138,82,No,72.9
47,27.0,126,144,87,Yes,76.2
36,24.9,114,122,76,No,67.25
53,29.1,130,148,89,Yes,79.05000000000001
40,26.0,119,132,81,No,71.3
61,31.5,136,162,96,Yes,84.94999999999999
39,23.8,117,128,77,No,68.60000000000001
49,27.5,129,146,90,Yes,77.75
37,24.5,116,124,79,No,68.15
54,30.0,133,150,91,Yes,80.6999999999999

In [2]:
import pandas as pd
import numpy as np


In [3]:
df = pd.read_csv('/content/diabetic_scores.txt')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Age              20 non-null     int64  
 1   BMI              20 non-null     float64
 2   Blood Pressure   20 non-null     int64  
 3   Glucose Level    20 non-null     int64  
 4   Insulin Level    20 non-null     int64  
 5   Diabetic Status  20 non-null     object 
 6   diabetic_score   20 non-null     float64
dtypes: float64(2), int64(4), object(1)
memory usage: 1.2+ KB


In [6]:
# step 1 : input matrix(feature matrix)
xdf = df.drop(['Diabetic Status','diabetic_score'],axis=1)
xdf.head()

Age   BMI  Blood Pressure  Glucose Level  Insulin Level
0   45  25.3             120            140             85
1   50  28.1             130            155             90
2   38  23.5             115            110             75
3   60  31.2             135            160             95
4   55  29.8             128            150             92

In [8]:
X = xdf.to_numpy()
X.shape

(20, 5)

In [9]:
df.head()

Age   BMI  Blood Pressure  ...  Insulin Level  Diabetic Status diabetic_score
0   45  25.3             120  ...             85              Yes          73.15
1   50  28.1             130  ...             90              Yes          80.05
2   38  23.5             115  ...             75               No          64.25
3   60  31.2             135  ...             95              Yes          84.10
4   55  29.8             128  ...             92              Yes          79.70

[5 rows x 7 columns]

In [10]:
Y = df['diabetic_score'].to_numpy()
Y.shape

(20,)

In [13]:
# model object
model = LinearRegression()
# train model
model.fit(X,Y)
# test accuracy
from sklearn.metrics import r2_score
Ycap = model.predict(X)
Ycap

array([73.15, 80.05, 64.25, 84.1 , 79.7 , 61.35, 71.85, 76.45, 66.45,
       82.55, 72.9 , 76.2 , 67.25, 79.05, 71.3 , 84.95, 68.6 , 77.75,
       68.15, 80.7 ])

In [14]:
np.c_[Y,Ycap]

array([[73.15, 73.15],
       [80.05, 80.05],
       [64.25, 64.25],
       [84.1 , 84.1 ],
       [79.7 , 79.7 ],
       [61.35, 61.35],
       [71.85, 71.85],
       [76.45, 76.45],
       [66.45, 66.45],
       [82.55, 82.55],
       [72.9 , 72.9 ],
       [76.2 , 76.2 ],
       [67.25, 67.25],
       [79.05, 79.05],
       [71.3 , 71.3 ],
       [84.95, 84.95],
       [68.6 , 68.6 ],
       [77.75, 77.75],
       [68.15, 68.15],
       [80.7 , 80.7 ]])

In [16]:
acc = r2_score(Y,Ycap)*100
acc

100.0

In [17]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
model.fit(X,Y)
Ycap = model.predict(X)
acc = r2_score(Y,Ycap)*100
acc

100.0

In [19]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=10)
model.fit(X,Y)
Ycap = model.predict(X)
acc = r2_score(Y,Ycap)*100
acc

99.03439935482378

In [25]:
from sklearn.svm import SVR
model = SVR(kernel='linear') # other options --> p
model.fit(X,Y)
Ycap = model.predict(X)
acc = r2_score(Y,Ycap)*100
acc

99.98909384146621

In [22]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor()
model.fit(X,Y)
Ycap = model.predict(X)
acc = r2_score(Y,Ycap)*100
acc

96.36588105299371

In [23]:
from sklearn.neural_network import MLPRegressor
model = MLPRegressor()
model.fit(X,Y)
Ycap = model.predict(X)
acc = r2_score(Y,Ycap)*100
acc

38.586447309946706



```
# This is formatted as code
```
input file : diabetic.txt

Age,BMI,Blood Pressure,Glucose Level,Insulin Level,Diabetic Status
45,25.3,120,140,85,Yes
50,28.1,130,155,90,Yes
38,23.5,115,110,75,No
60,31.2,135,160,95,Yes
55,29.8,128,150,92,Yes
32,22.7,110,105,70,No
42,26.5,118,135,80,No
48,27.3,125,145,88,Yes
35,24.1,113,120,78,No
58,30.5,132,158,93,Yes
41,25.8,121,138,82,No
47,27.0,126,144,87,Yes
36,24.9,114,122,76,No
53,29.1,130,148,89,Yes
40,26.0,119,132,81,No
61,31.5,136,162,96,Yes
39,23.8,117,128,77,No
49,27.5,129,146,90,Yes
37,24.5,116,124,79,No
54,30.0,133,150,91,Yes
46,26.1,122,142,86,Yes
51,28.5,131,156,91,Yes
34,23.1,111,108,72,No
62,32.0,137,164,97,Yes
56,30.0,129,152,93,Yes
30,22.0,109,104,68,No
43,27.0,119,136,81,No
49,28.0,124,146,89,Yes
33,24.0,112,118,75,No
59,31.0,134,160,94,Yes
42,26.7,122,140,83,No
48,28.2,127,149,88,Yes
36,24.2,115,121,77,No
52,29.5,129,151,90,Yes
39,25.5,120,130,80,No
63,32.5,138,165,98,Yes
37,24.3,118,125,78,No
50,27.8,130,147,91,Yes
35,24.6,117,123,76,No
55,30.5,132,153,92,Yes


In [26]:
df = pd.read_csv('/content/diabetic.txt')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Age              40 non-null     int64  
 1   BMI              40 non-null     float64
 2   Blood Pressure   40 non-null     int64  
 3   Glucose Level    40 non-null     int64  
 4   Insulin Level    40 non-null     int64  
 5   Diabetic Status  40 non-null     object 
dtypes: float64(1), int64(4), object(1)
memory usage: 2.0+ KB


In [27]:
df['dstat'] = np.where(df['Diabetic Status']=='Yes',1,0)
df.head()

Age   BMI  Blood Pressure  ...  Insulin Level  Diabetic Status dstat
0   45  25.3             120  ...             85              Yes     1
1   50  28.1             130  ...             90              Yes     1
2   38  23.5             115  ...             75               No     0
3   60  31.2             135  ...             95              Yes     1
4   55  29.8             128  ...             92              Yes     1

[5 rows x 7 columns]

In [28]:
xdf = df.drop(['Diabetic Status','dstat'],axis=1)
xdf.head()

Age   BMI  Blood Pressure  Glucose Level  Insulin Level
0   45  25.3             120            140             85
1   50  28.1             130            155             90
2   38  23.5             115            110             75
3   60  31.2             135            160             95
4   55  29.8             128            150             92

In [30]:
X = xdf.to_numpy()
X.shape

(40, 5)

In [31]:
Y = df['dstat'].to_numpy()
Y

array([1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [32]:
Y.shape

(40,)

In [33]:
# experiment with logistic regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X,Y)
Ycap = model.predict(X)
from sklearn.metrics import accuracy_score
acc = accuracy_score(Y,Ycap)*100
acc

100.0

In [34]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X,Y)
Ycap = model.predict(X)
from sklearn.metrics import accuracy_score
acc = accuracy_score(Y,Ycap)*100
acc

97.5

In [37]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X,Y)
Ycap = model.predict(X)
from sklearn.metrics import accuracy_score
acc = accuracy_score(Y,Ycap)*100
acc

100.0

In [38]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X,Y)
Ycap = model.predict(X)
from sklearn.metrics import accuracy_score
acc = accuracy_score(Y,Ycap)*100
acc

100.0

In [40]:
from sklearn.svm import SVC
model = SVC(kernel ='linear')
model.fit(X,Y)
Ycap = model.predict(X)
from sklearn.metrics import accuracy_score
acc = accuracy_score(Y,Ycap)*100
acc

100.0